### ISSUE TITLE
non-leaf frames on Windows show off-by-one source/line

### ISSUE THREAD

**Issue by milianw** [milostosic/MTuner#33]
the non-leaf frames on Windows are often off-by-one when looking at the reported source/line. See the following screenshot for an example:

![off-by-one-callstack](https://user-images.githubusercontent.com/57207/33283138-32f90836-d3ab-11e7-82b4-171474fc81e5.png)

Note how the call stack tree shows the function countWords, but the source view shows the line after that. The issue is probably that the calling function pushes the return address on the stack, and you'll need to account for that when looking for the call location.

**Comment by milostosic** [comment]
This is "by design", I'm using CaptureStackBackTrace for performance reasons and spending even more time in capturing stack traces (to fix call locations) is undesirable. On other platforms this may or may not work 'properly' - depending on how stack was walked.

Now, you can always opt for link time instrumentation of your code using MTuner SDK [(rmem](https://github.com/milostosic/rmem) library) and modify the way stack is walked to get accurate results if this is important for you.

**Comment by milianw** [comment]
Shouldn't this be done offline, i.e. after the trace? Simply offset the non-leaf frames by one before finding the file/line location. This is how the profilers I know of operate - i.e. they only do the fast stack walking at trace/profile time. Then, later in a separate step when analyzing the trace do they actually spend time on finding e.g. file/line locations and resolving symbol names etc.

I suggest reconsidering this.

**Comment by milostosic** [comment]
It's possible you're right, I just never saw this as problem.
I'll put it in my backlog but as I mentioned before - I both have limited time and other projects I work on (besides a full time job, kid, etc.).

With that being said, why not contribute? :)
