### ISSUE TITLE
No function names

### ISSUE THREAD

**Issue by tim-lebedkov** [milostosic/MTuner#46]
I have a .pdb file generated by cv2pdb, _NT_SYMBOL_PATH pointing to the directory with .exe and .pdb, the checkbox for _NT_SYMBOL_PAT under Settings/Debug symbols is also on.

![grafik](https://user-images.githubusercontent.com/831371/57218554-dd2e9900-6ff5-11e9-9cfe-f1ad47db5c25.png)

**Comment by tim-lebedkov** [comment]
It seems that MTuner does not even try to load the .pdb file

![grafik](https://user-images.githubusercontent.com/831371/57237799-416a5080-7028-11e9-8872-25c9edce848c.png)

**Comment by milostosic** [comment]
Hi, sorry but I was away from GitHub for a while.
Do you mind sending me a repro so I can debug it locally? It would save me time fixing this issue.

**Comment by tim-lebedkov** [comment]
[TestMTuner.zip](https://github.com/milostosic/MTuner/files/3305736/TestMTuner.zip)
![grafik](https://user-images.githubusercontent.com/831371/59760249-2a0ebc00-9292-11e9-9c8d-945db09d2ff1.png)
![grafik](https://user-images.githubusercontent.com/831371/59760290-41e64000-9292-11e9-815f-1e1b5c215a66.png)

You can run dist\TestMTuner.exe from TestMTuner.zip

**Comment by tim-lebedkov** [comment]
The value of _NT_SYMBOL_PATH:

![grafik](https://user-images.githubusercontent.com/831371/59760400-88d43580-9292-11e9-9a5e-6a12e726a2bc.png)

![grafik](https://user-images.githubusercontent.com/831371/59760436-9e495f80-9292-11e9-9cb9-00048aa3ae82.png)

**Comment by milostosic** [comment]
Thanks, I'll check it out soon.

**Comment by milostosic** [comment]
Hi, I've worked on this and there are positive results. However, I am not fully pleased as I am yet to understand why IDiaDataSource::loadDataForExe fails to find PDB file for the executable with the test case you sent. 

However, I've made a few fixes/improvements and symbols are now loaded. MTuner will try to load a PDB file with a matching name in the same directory where EXE resides - it's a bit of a hacky workaround but it works. You can get the build v4.1.7 and check it out.

A small note - making 2 billion memory operations for a test case is an overkill :)

![mtuner_symbols](https://user-images.githubusercontent.com/1654399/59978240-fa064680-960c-11e9-9f0d-4d097260483e.png)

**Comment by tim-lebedkov** [comment]
Thank You!

**Comment by Codinablack** [comment]
I'm currently suffering from this problem and it's a nightmare for me... It took sooooooooooooo much of my time to get this memory capture of the leak with this tool, only for it to show ABSOLUTELY NOTHING USEFUL because there are no function names... I have a pdb generated IN THE SAME FOLDER AS THE EXE (and yes with the same name) as per instructions, its full debug symbols too, I literally only build in debug mode ever, and its 64bit too.... what I'm noticing is it's not even letting me check that box for _NT_SYMBOL_PATH...

<img width="482" height="439" alt="Image" src="https://github.com/user-attachments/assets/c186fa17-48b7-4b96-95ef-9fcc1ded83fd" />


Please help me figure out what I'm doing wrong, I know in the past I have used this tool without such a problem, no clue why it's an issue now
